//! The closed subtype vocabulary. CR 205.3.
//!
//! Generated from the card corpus, which is the same MTGJSON data the engine
//! builds its own subtype knowledge from. It is embedded rather than guessed at
//! because English morphology cannot recover a Magic subtype from its plural:
//! "Zombies" is Zombie plus s, "Allies" is Ally plus ies, "Elves" is Elf plus
//! ves, and "Plains", "Octopus" and "Fungus" are singular already. Any rule
//! that gets three of those right gets the fourth wrong.
//!
//! Regenerate with the script in HANDOFF.md when a new set adds types.

/// Every printed subtype, sorted.
const SUBTYPES: &[&str] = &[
    "Abian",
    "Adventure",
    "Advisor",
    "Aetherborn",
    "Ajani",
    "Alara",
    "Alfava Metraxis",
    "Alicorn",
    "Alien",
    "Ally",
    "Aminatou",
    "Amonkhet",
    "Amsterdam",
    "Andorian",
    "Androzani Minor",
    "Angel",
    "Angrath",
    "Antausia",
    "Antelope",
    "Apalapucia",
    "Ape",
    "Arcane",
    "Arcavios",
    "Archer",
    "Archon",
    "Arkhos",
    "Arlinn",
    "Armadillo",
    "Armored",
    "Art",
    "Artificer",
    "Artist",
    "Arzakon",
    "Ashiok",
    "Assassin",
    "Assembly-Worker",
    "Astartes",
    "Athlete",
    "Atog",
    "Attraction",
    "Aura",
    "Aurochs",
    "Autobot",
    "Avatar",
    "Avishkar",
    "Azgol",
    "Azra",
    "Background",
    "Badger",
    "Bahamut",
    "Barbarian",
    "Bard",
    "Barnyard",
    "Basilisk",
    "Basri",
    "Bat",
    "Bear",
    "Beast",
    "Beaver",
    "Beeble",
    "Beholder",
    "Belenon",
    "Berserker",
    "Bird",
    "Bison",
    "Blind Eternities",
    "Bloomburrow",
    "Boar",
    "Bobblehead",
    "Bolas",
    "Bolas's Meditation Realm",
    "Book",
    "Borg",
    "Boxer",
    "Brainiac",
    "Bringer",
    "Brushwagg",
    "Bureaucrat",
    "Byode",
    "C'tan",
    "Caitian",
    "Calix",
    "Camel",
    "Capenna",
    "Capybara",
    "Carrier",
    "Cartouche",
    "Case",
    "Cat",
    "Cave",
    "Centaur",
    "Cephalid",
    "Chameleon",
    "Champion",
    "Chandra",
    "Chef",
    "Chicago",
    "Chicken",
    "Child",
    "Chimera",
    "Chorus",
    "Citizen",
    "Clamfolk",
    "Clamhattan",
    "Class",
    "Cleric",
    "Cloud",
    "Clown",
    "Clue",
    "Cockatrice",
    "Comet",
    "Construct",
    "Contraption",
    "Control",
    "Cow",
    "Coward",
    "Coyote",
    "Crab",
    "Cridhe",
    "Crocodile",
    "Curse",
    "Custodes",
    "Cyberman",
    "Cyborg",
    "Cyclops",
    "Dack",
    "Dakkon",
    "Dalek",
    "Daretti",
    "Darillium",
    "Dauthi",
    "Davriel",
    "Deb",
    "Deer",
    "Dellian",
    "Demigod",
    "Demon",
    "Desert",
    "Designer",
    "Detective",
    "Devil",
    "Dihada",
    "Dinosaur",
    "Djinn",
    "Doctor",
    "Dog",
    "Dominaria",
    "Domri",
    "Donkey",
    "Dovin",
    "Dragon",
    "Drake",
    "Dreadnought",
    "Drix",
    "Drone",
    "Druid",
    "Dryad",
    "Duck",
    "Dungeon",
    "Duskmourn",
    "Dwarf",
    "Dyfed",
    "Earth",
    "Echidna",
    "Echoir",
    "Efreet",
    "Egg",
    "Elder",
    "Eldraine",
    "Eldrazi",
    "Elemental",
    "Elephant",
    "Elf",
    "Elk",
    "Ellywick",
    "Elminster",
    "Elspeth",
    "Elves",
    "Employee",
    "Equilor",
    "Equipment",
    "Ergamon",
    "Ersta",
    "Estrid",
    "Eternal",
    "Etiquette",
    "Eye",
    "Fabacin",
    "Faerie",
    "Feroz",
    "Ferret",
    "Fiora",
    "Fire",
    "Fish",
    "Flagbearer",
    "Foldaria",
    "Food",
    "Forest",
    "Fortification",
    "Foundations",
    "Fox",
    "Fractal",
    "Freyalise",
    "Frog",
    "Fungus",
    "Gallifrey",
    "Gamer",
    "Gamma",
    "Gargantikar",
    "Gargoyle",
    "Garruk",
    "Gate",
    "Giant",
    "Gideon",
    "Giraffe",
    "Gith",
    "Glimmer",
    "Gnoll",
    "Gnome",
    "Goat",
    "Gobakhan",
    "Goblin",
    "God",
    "Golem",
    "Gorgon",
    "Gorn",
    "Grandchild",
    "Greensleeves",
    "Gremlin",
    "Griffin",
    "Grist",
    "Guest",
    "Guff",
    "Gus",
    "Hag",
    "Halfling",
    "Hamster",
    "Harpy",
    "Hatificer",
    "Hawk",
    "Head",
    "Hedgehog",
    "Hell",
    "Hellion",
    "Hero",
    "Hippo",
    "Hippogriff",
    "Homarid",
    "Homunculus",
    "Horror",
    "Horse",
    "Horsehead Nebula",
    "Huatli",
    "Human",
    "Hydra",
    "Hyena",
    "Igpay",
    "Ikoria",
    "Illusion",
    "Imp",
    "Incarnation",
    "Infinity",
    "Inhuman",
    "Inkling",
    "Innistrad",
    "Inquisitor",
    "Insect",
    "Inzerva",
    "Iquatana",
    "Ir",
    "Island",
    "Ixalan",
    "Jace",
    "Jackal",
    "Jared",
    "Jaya",
    "Jellyfish",
    "Jeska",
    "Judge",
    "Juggernaut",
    "Kaito",
    "Kaldheim",
    "Kamigawa",
    "Kandoka",
    "Kangaroo",
    "Karn",
    "Karsus",
    "Kasmina",
    "Kavu",
    "Kaya",
    "Kelpien",
    "Kephalai",
    "Key",
    "Killbot",
    "Kinshala",
    "Kiora",
    "Kirin",
    "Kithkin",
    "Klingon",
    "Knight",
    "Koala",
    "Kobold",
    "Kolbahan",
    "Kor",
    "Koth",
    "Kraken",
    "Kree",
    "Kylem",
    "Kyneth",
    "LaIR",
    "Lady",
    "Lair",
    "Lamia",
    "Lammasu",
    "Lander",
    "Lanthanite",
    "Las Vegas",
    "Leech",
    "Lemur",
    "Lesson",
    "Leviathan",
    "Lhurgoyf",
    "Licid",
    "Liliana",
    "Lizard",
    "Lobster",
    "Locus",
    "Lolth",
    "Lorwyn",
    "Lukka",
    "Luvion",
    "Luxior",
    "MagicCon",
    "Mammoth",
    "Manticore",
    "Mars",
    "Master",
    "Masticore",
    "Mercadia",
    "Mercenary",
    "Merfolk",
    "Metathran",
    "Mime",
    "Mine",
    "Minion",
    "Minotaur",
    "Minsc",
    "Mirrodin",
    "Mission",
    "Mite",
    "Moag",
    "Mole",
    "Monger",
    "Mongoose",
    "Mongseng",
    "Monk",
    "Monkey",
    "Monopoly",
    "Moogle",
    "Moon",
    "Moonfolk",
    "Mordenkainen",
    "Mount",
    "Mountain",
    "Mouse",
    "Mummy",
    "Muraganda",
    "Mutant",
    "Myr",
    "Mystic",
    "Nahiri",
    "Narset",
    "Nautilus",
    "Necron",
    "Necros",
    "Nephilim",
    "New Earth",
    "New Phyrexia",
    "Nightmare",
    "Nightstalker",
    "Niko",
    "Ninja",
    "Nissa",
    "Nixilis",
    "Noble",
    "Noggle",
    "Nomad",
    "Nymph",
    "Octopus",
    "Officer",
    "Ogre",
    "Oko",
    "Omen",
    "Omenpath",
    "Ooze",
    "Orc",
    "Orgg",
    "Orion",
    "Otter",
    "Ouphe",
    "Outside Mutter's Spiral",
    "Ox",
    "Oyster",
    "Pangolin",
    "Paratrooper",
    "Peasant",
    "Pegasus",
    "Penguin",
    "Performer",
    "Pest",
    "Phelddagrif",
    "Phoenix",
    "Phyrexia",
    "Phyrexian",
    "Pilot",
    "Pirate",
    "Plains",
    "Plan",
    "Planet",
    "Plant",
    "Platypus",
    "Point",
    "Pony",
    "Porcupine",
    "Possum",
    "Power-Plant",
    "Powerstone",
    "Praetor",
    "Primarch",
    "Processor",
    "Proper",
    "Pyrulea",
    "Q",
    "Qu",
    "Quest",
    "Quintorius",
    "Rabbit",
    "Rabiah",
    "Raccoon",
    "Ral",
    "Ranger",
    "Rat",
    "Rath",
    "Ravnica",
    "Realm",
    "Rebel",
    "Reflection",
    "Regatha",
    "Rhino",
    "Rigger",
    "Robot",
    "Rogue",
    "Room",
    "Rowan",
    "Rune",
    "Sable",
    "Saga",
    "Saheeli",
    "Salamander",
    "Samurai",
    "Samut",
    "Sand",
    "Saproling",
    "Sarkhan",
    "Satyr",
    "Scarecrow",
    "Scientist",
    "Scorpion",
    "Scout",
    "Seal",
    "Secret",
    "Secret Lair",
    "Segovia",
    "Serpent",
    "Serra",
    "Serra's Realm",
    "Shade",
    "Shadowmoor",
    "Shaman",
    "Shandalar",
    "Shapeshifter",
    "Shark",
    "Sheep",
    "Shenmeng",
    "Shi'ar",
    "Ship",
    "Shrine",
    "Siege",
    "Sifa",
    "Siren",
    "Sivitri",
    "Skaro",
    "Skeleton",
    "Skrull",
    "Skunk",
    "Slith",
    "Sliver",
    "Sloth",
    "Slug",
    "Snail",
    "Snake",
    "Soldier",
    "Soltari",
    "Sorcerer",
    "Sorin",
    "Spacecraft",
    "Spawn",
    "Specter",
    "Spellshaper",
    "Sphere",
    "Sphinx",
    "Spider",
    "Spike",
    "Spirit",
    "Splinter",
    "Sponge",
    "Spuzzem",
    "Spy",
    "Squid",
    "Squirrel",
    "Starfish",
    "Stone",
    "Surrakar",
    "Survivor",
    "Svega",
    "Swamp",
    "Symbiote",
    "Synth",
    "Szat",
    "Talosian",
    "Tamiyo",
    "Tarkir",
    "Tasha",
    "Teferi",
    "Tellarite",
    "Teyo",
    "Tezzeret",
    "Thalakos",
    "The",
    "The Abyss",
    "The Dalek Asylum",
    "The Library",
    "Theros",
    "Tholian",
    "Thomil",
    "Thopter",
    "Thrull",
    "Thunder Junction",
    "Tibalt",
    "Tiefling",
    "Time",
    "Time Lord",
    "Tosk",
    "Tower",
    "Town",
    "Townsfolk",
    "Toy",
    "Trap",
    "Treasure",
    "Tree",
    "Treefolk",
    "Trenzalore",
    "Trilobite",
    "Troll",
    "Turtle",
    "Tyranid",
    "Tyvar",
    "Ugin",
    "Ulamog's",
    "Ulgrotha",
    "Unicorn",
    "Universia Beyondia",
    "Unknown Planet",
    "Urza",
    "Urza's",
    "Utrom",
    "Valla",
    "Vampire",
    "Vampyre",
    "Varmint",
    "Vedalken",
    "Vehicle",
    "Venser",
    "Villain",
    "Vivien",
    "Volver",
    "Vorta",
    "Vraska",
    "Vronos",
    "Vryn",
    "Vulcan",
    "Waiter",
    "Wall",
    "Walrus",
    "Wanderer",
    "Warlock",
    "Warrior",
    "Weasel",
    "Weird",
    "Werewolf",
    "Whale",
    "Wildfire",
    "Will",
    "Windgrace",
    "Wizard",
    "Wolf",
    "Wolverine",
    "Wombat",
    "Worm",
    "Worzel",
    "Wraith",
    "Wrenn",
    "Wrestler",
    "Wurm",
    "Xenagos",
    "Xerex",
    "Xindi",
    "Yanggu",
    "Yanling",
    "Yeti",
    "You",
    "Zariel",
    "Zendikar",
    "Zhalfir",
    "Zombie",
    "Zonian",
    "Zubera",
    "of",
    "sECreT",
];

/// Resolve a printed noun to the subtype it names, singularizing if needed.
///
/// Tries the word as printed first, so a subtype that is ALREADY singular and
/// merely ends in `s` ("Plains", "Octopus") is never mangled. Only then does it
/// try the plural forms, each of which is a real English pattern rather than a
/// guess: `-s`, `-es`, `-ies` to `-y`, `-ves` to `-f`.
pub fn singular_of(word: &str) -> Option<&'static str> {
    // Plural patterns are tried FIRST, because a few plurals are themselves
    // listed subtypes: "Elves" is on Elvish Impersonators' type line, but
    // "other Elves you control" means Elf. Trying the singular first resolves
    // the common reading; a subtype that is genuinely singular and merely ends
    // in `s` ("Plains", "Octopus", "Fungus") has no valid singularization and
    // falls through to the exact match below.
    let candidates = [
        word.strip_suffix("ies").map(|s| format!("{s}y")),
        word.strip_suffix("ves").map(|s| format!("{s}f")),
        word.strip_suffix("es").map(str::to_string),
        word.strip_suffix('s').map(str::to_string),
    ];
    candidates
        .iter()
        .flatten()
        .find_map(|candidate| lookup(candidate))
        .or_else(|| lookup(word))
}

/// Case-insensitive membership, yielding the canonically-cased spelling.
fn lookup(word: &str) -> Option<&'static str> {
    SUBTYPES
        .iter()
        .copied()
        .find(|s| s.eq_ignore_ascii_case(word))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recovers_a_subtype_from_each_english_plural_pattern() {
        assert_eq!(singular_of("Zombies"), Some("Zombie"));
        // "Elves" is itself a listed subtype; the singular still wins.
        assert_eq!(singular_of("Elves"), Some("Elf"));
        assert_eq!(singular_of("Allies"), Some("Ally"));
        assert_eq!(singular_of("Elves"), Some("Elf"));
        assert_eq!(singular_of("Soldiers"), Some("Soldier"));
    }

    #[test]
    fn leaves_a_singular_subtype_that_ends_in_s_alone() {
        // The whole reason the list is embedded rather than derived.
        assert_eq!(singular_of("Plains"), Some("Plains"));
        assert_eq!(singular_of("Octopus"), Some("Octopus"));
        assert_eq!(singular_of("Fungus"), Some("Fungus"));
    }

    #[test]
    fn declines_a_word_that_is_not_a_subtype() {
        assert_eq!(singular_of("Untap"), None);
        assert_eq!(singular_of("It"), None);
    }

    #[test]
    fn matches_case_insensitively_but_yields_the_printed_casing() {
        assert_eq!(singular_of("goblin"), Some("Goblin"));
    }
}
